### ISSUE TITLE
Stars taking time to disappear

### ISSUE THREAD

**Issue by Arrocha08** [Nettakrim/Spyglass-Astronomy#11]
Even when is day time the stars take a long time to disapear from the skies, and when it does simply disapear quickly, I think it would be more clean if it fades away

**Comment by Nettakrim** [comment]
vanilla stars do the same thing, personally i like how it looks
the stars slowly fade away for around the duration of there being reddish-orange around the sun, which lasts a perhaps surprising amount of time into the day

**Comment by Arrocha08** [comment]
My bad. I test it again and find out that the problem actually was with my shaders pack. Im playing with ComplementaryReimagined_r1.3.2, but I also test:
-rethinking-voxels_beta18d
-projectLUMA+-+v1.32
-BSL_v8.2.03

and shows the same problem. That didnt happend with others shaders, but also your mod doesnt work, only with the ones a mentioned above, which coincidentally are shaders that mixes your mod with its own skies.
It happens around "/time set 24500"

https://github.com/Nettakrim/Spyglass-Astronomy/assets/105840060/ceece15a-2f64-463a-89bc-77f0af40e41f

I dont know if it can be fixed

**Comment by Nettakrim** [comment]
ah
im suprised any realistic shaders work at all with it, they tend to mess with stars a bit too much for it to work properly

**Comment by Arrocha08** [comment]
Thanks for you time
