### ISSUE TITLE
World closes and close the game when loading a world in 1.20.1

### ISSUE THREAD

**Issue by IGRTs** [Nettakrim/Spyglass-Astronomy#13]
When you boot up the game even without any other mods, only with the Spyglass-Astronomy and the Fabric API, and you try to load a world, it makes all the loading counting and animation, but on the "Entering World" it automaticaly goes to "Saving World" and then closes the game.

Here are the log:

[latest.log](https://github.com/Nettakrim/Spyglass-Astronomy/files/11964880/latest.log)

**Comment by Nettakrim** [comment]
ah by the looks of the error, the name of your world contains a `|` character, which it doesn't like - next update i can fix this, in the mean time just renaming your world to filesystem friendly name should allow it to load
