### ISSUE TITLE
[1.20.1] Crash with the new sodium 0.5.0

### ISSUE THREAD

**Issue by EnderMelody** [Nettakrim/Spyglass-Astronomy#14]
minecraft: 1.20.1
quilt: 0.19.2
sodium: 0.5.0 build 111
game crashes when loading into a world with the new sodium update.

[crash-2023-08-05_11.28.39-client.txt](https://github.com/Nettakrim/Spyglass-Astronomy/files/12267612/crash-2023-08-05_11.28.39-client.txt)

**Comment by Amronos** [comment]
having similar issues
edit: it may also be because of the spyglass improvements mod

**Comment by Nettakrim** [comment]
spyglass improvements is only compatible on a few versions - mojang also recently changed the incompatible bit of code in such a way that makes it harder to make compatible, ill see if i can fix it

thats a weird crash report, ill investigate

**Comment by Nettakrim** [comment]
hmm i cant reproduce the sodium issue, however the crash report does give me enough information to potentially fix it

**Comment by EnderMelody** [comment]
it might not be sodium causing the problem but one of the supporting mods, ive just been having to fix a lot of mods since the sodium update so i dont remember how much i tested it. ill check again when i have time later hopefully.

**Comment by Nettakrim** [comment]
if you download the build result of the latest commit [here](https://github.com/Nettakrim/Spyglass-Astronomy/actions/runs/5776973992) or just click [this](https://github.com/Nettakrim/Spyglass-Astronomy/suites/14861664182/artifacts/846345107) - it should have a version with the potential fix

ofc ideally knowing what the incompatibility is would be good

**Comment by Nettakrim** [comment]
it also seems to work with spyglass improvements? which is weird i wouldve thought it wouldnt

**Comment by EnderMelody** [comment]
i did use spyglass improvements with this mod for a while and it worked perfectly fine.

**Comment by Nettakrim** [comment]
some versions do, some dont, im suprised it works in the current version

**Comment by EnderMelody** [comment]
so i tested the mod again in my pack and now i can load in just fine so im not sure what was causing the problem before. i did remove some mods before testing but i dont remember which ones. i can say its not a problem with sodium or its addons at least.
