### ISSUE TITLE
Suggestion: Double click on a recently drawn constellation line to remove it

### ISSUE THREAD

**Issue by Trinketina** [Nettakrim/Spyglass-Astronomy#16]
I've found when drawing constellations I want almost an, undo button of sorts, drawing between the stars is really smooth but as far as I've been able to tell, once a line is drawn there's no way to remove it without deleting the constellation?
 
It'd be nice to have the ability to edit a constellation you recently made, so maybe adding a double click on a line between two stars could delete it?

**Comment by Nettakrim** [comment]
drawing again between the two stars removes the line

**Comment by Trinketina** [comment]
Oh!! I'm just dumb and didn't figure that out sorry!
