### ISSUE TITLE
Invisible comet?

### ISSUE THREAD

**Issue by Emelydia** [Nettakrim/Spyglass-Astronomy#21]
One of the 4 comets on my seed seems to be completely invisible. It's always very close at only 0.99-1.01 AU distance at all times. I stumbled across it by accident while trying to find the 2 comets I hadn't seen yet (this was one of them). The other 3 comets are all visible when they're supposed to be.

![Looking at Gamma](https://github.com/Nettakrim/Spyglass-Astronomy/assets/64650411/a22093f0-f967-4cf9-804e-77295ace6a29)
![Comet Info](https://github.com/Nettakrim/Spyglass-Astronomy/assets/64650411/2609b331-3391-43f6-b480-a6e514e550cf)

Note: the stars work like intended. I just disabled them to find the comets.

Versions: 
- Minecraft 1.20.1
- Fabric Loader 0.15.3
- Spyglass Astronomy 1.0.8

All other mods in use:
![mods used](https://github.com/Nettakrim/Spyglass-Astronomy/assets/64650411/f7e2a350-7359-4064-b88e-3766c0104b97)
(also using a resource pack that makes the spyglass lens more transparent)

**Comment by Nettakrim** [comment]
that is weird, looking at the orbital parameters the info command is giving, the fact that its only 1 AU away must be because you caught it at its closest approach? it should spend much of its time >20 AU away

if you send me the planet seed (which you can get from one of the admin commands) i can see if i can reproduce the issue - it might just be that it generated near the lowest possible albedo of 0.125, as if it were some dark rocky asteroid

**Comment by Nettakrim** [comment]
looking at the code, as long as the comet is within 4 AU it should be visible from Y 255, even with the lowest possible albedo

**Comment by Emelydia** [comment]
Planet seed is 6301639858448075734. 
I tracked the comet's position in the sky 48 times with 1000t intervals starting from 0. I also checked it on a couple random nights throughout its 88-day orbital period, but those aren't tracked on a spreadsheet. It's always at a distance of 0.99-1.01 AU, it's always at 0% orbit completion, and it's never visible. It's by far the closest comet on this seed: the other comets have orbital periods of 514, 616 and 1104 days. It's also the closest object outright quite frequently.
![image](https://github.com/Nettakrim/Spyglass-Astronomy/assets/64650411/b100d383-59b6-461e-9c68-6d905070b48b)

**Comment by Nettakrim** [comment]
thats interesting, ill investigate shortly but my immediate thought looking at the 1 AU distance and 0% position is making me think its locked at the solar systems "0 0 0" so the variation in distance is just the slight eccentricity of thisworld - although in that case it should always appear near the sun? perhaps theres some discrepancy between rendered position and actual position

definately suspicious of some kind of null or infinity or 0 where there shouldn't be

this is a really funny bug conceptually

**Comment by Nettakrim** [comment]
the comet is indeed located at 0 0 0

**Comment by Nettakrim** [comment]
aha! its kepler's fault! (indirectly, its mostly my fault, although the kepler lookup was responsible for it not just crashing)

**Comment by Nettakrim** [comment]
lmao its an obvious division by 0 error

**Comment by Nettakrim** [comment]
![image](https://github.com/Nettakrim/Spyglass-Astronomy/assets/106409257/fa65d225-37ad-43c9-be37-d0100fb85fd7)

this just straight up applies to the first comet in every world omg

**Comment by Nettakrim** [comment]
![image](https://github.com/Nettakrim/Spyglass-Astronomy/assets/106409257/4b3e8a16-be7a-4dd0-a296-13eee97503c3)
theres your missing comet! the next sga update will have 26% more comets!
