### ISSUE TITLE
[1.20.1] Conflicting mixing causes crash with another mod: Bank Storage

### ISSUE THREAD

**Issue by Natanaelel** [Nettakrim/Spyglass-Astronomy#24]
This is because both bankstorage and spyglass astronomy tries to replace the same minecraft code. (I'm the author of bank storage)
Bankstorage here: https://github.com/Natanaelel/BankStorage/blob/ff2c948daf92af6d142541cdf0aa77c7d09429bc/src/client/java/net/natte/bankstorage/mixin/MouseMixin.java#L18
Spyglass astronomy here: https://github.com/Nettakrim/Spyglass-Astronomy/blob/70f07ff1e69b2f8f6960f039bada19144a15abb1/src/main/java/com/nettakrim/spyglass_astronomy/mixin/MouseMixin.java#L35

Both bankstorage and spyglass astronomy is at fault here. I will fix it on my side and sga should too.

https://github.com/Natanaelel/BankStorage/issues/13

**Comment by Nettakrim** [comment]
https://github.com/LlamaLad7/MixinExtras/wiki/WrapWithCondition does what we want i think, as long were using a recent fabric loader version

**Comment by Natanaelel** [comment]
This works. Done on my end.

**Comment by Nettakrim** [comment]
ooh thats fun github automatically detected that i was not expecting that
