### ISSUE TITLE
Crash | Game crashing instantly when leaving Overworld, apon reloading it lets you into the dimension you entered. but apon leaving it. your game crashes again

### ISSUE THREAD

**Issue by KaidKM3** [Nettakrim/Spyglass-Astronomy#25]
Logs below.
the latest log is without a mod called bobby, i was told it had problems. the log before that crashed with bobby
What is erroring when going to the nether or end
i looked at it myself it is mentioning Boolean error and SpaceDataManager.

[2024-02-11-1.log.gz](https://github.com/Nettakrim/Spyglass-Astronomy/files/14231759/2024-02-11-1.log.gz)
[latest.log](https://github.com/Nettakrim/Spyglass-Astronomy/files/14231760/latest.log)

**Comment by Nettakrim** [comment]
ah interesting i think both sga and bobby have this same crash because i used the same method as bobby for checking server name

**Comment by Nettakrim** [comment]
it does seem to work fine on .4 though, now im wondering if the 1.20.2+ version might actually work on .1??, give it a shot i guess but its unlikely

**Comment by KaidKM3** [comment]
Alright. I'll try that now. Im going to see if it works.
I'll put another Log if it fails again.

**Comment by KaidKM3** [comment]
The Latest 1.20.2 Version crashed the same way by going through a portal.
[latest.log](https://github.com/Nettakrim/Spyglass-Astronomy/files/14378152/latest.log)
Heres The log.

**Comment by KaidKM3** [comment]
Sorry i thought i put this information in on how to replicate the problem.

When i had Spyglass astronomy Installed Before naming planets, comets, stars, and made constellations. everything worked fine.

After i named a few stars, comets, planets, constellations. That is when the Crash when loading the nether started to occur.

**Comment by Nettakrim** [comment]
oooh ok thats useful information

**Comment by Zunwolf1896** [comment]
I have the same issue here. Using MC version 1.20.1 (fabric 0.15.10) and Spyglass version 1.0.8

crash log here: https://mclo.gs/KyhDpPG

I TPd to the nether, game crashed. 

logged in, teleported myself to teh netehr spawn hub area, went through the portal and crashed aagin. This report is the second crash - from nether to overworld.

**Comment by KaidKM3** [comment]
I Dont believe the mod problem here has been fixed @Zunwolf1896 , Possibly the mod is (Maybe)* going to release a megapatch to fix all mentioned bugs to every version... You Never Know.

**Comment by Nettakrim** [comment]
its a really weird bug i have no idea what the cause is, i can probably do a silly fix though

**Comment by Nettakrim** [comment]
try this https://modrinth.com/mod/spyglass-astronomy/version/1.0.10.1

**Comment by Nettakrim** [comment]
ok it seems it has been fixed, however there is a separate issue where the sky doesnt like loading properly after going through a portal
