### ISSUE TITLE
Issue with constellations that are most visible at 0 Days into a year

### ISSUE THREAD

**Issue by KingCam77** [Nettakrim/Spyglass-Astronomy#31]
The time until they are most visible is broken, never consistent with the actual days

![image](https://github.com/Nettakrim/Spyglass-Astronomy/assets/43072336/9ae2e4ea-fa05-4b81-bef7-1d0c481c460f)

Here im 12 days into a year and it displays -4 days

**Comment by Nettakrim** [comment]
ahaha this was because i tried to account for things being 0 days by adding 8, when i shouldve added the period, thats funny
