### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by NolanHewitt** [Nettakrim/Spyglass-Astronomy#34]
[crash-2024-08-03_23.17.51-client.txt](https://github.com/user-attachments/files/16486283/crash-2024-08-03_23.17.51-client.txt)

**Comment by Nettakrim** [comment]
i remember seeing a crash like that

**Comment by Nettakrim** [comment]
ah yeah looks like i fixed it in 1.21, although i thought it was exclusive to that version

**Comment by Nettakrim** [comment]
weird that it happens in 1.20.1, i also wont be able to fix that for a while

**Comment by Fyoncle** [comment]
> weird that it happens in 1.20.1, i also wont be able to fix that for a while

Oh i really wanted to use this in my modpack! That's so unfortunate :(

**Comment by Nettakrim** [comment]
should be fixed in next 1.20.1 version
