### ISSUE TITLE
Option To Reduce Alpha Of Lens

### ISSUE THREAD

**Issue by Fyoncle** [Nettakrim/Spyglass-Astronomy#38]
Spyglass's lens can be a lot of distracting specially at night or while using this mod. So i tried to use [this resource pack](https://modrinth.com/resourcepack/clear-spyglass-scope) which disables itself when mode of the spyglass changed in Spyglass Astronomy, maybe either use vanilla lens so resource packs can override it? Or add a config to change transparency of the lens

**Comment by Fyoncle** [comment]
❤️

**Comment by Nettakrim** [comment]
https://modrinth.com/mod/spyglass-astronomy/version/1.0.14-mc1.21.2+

**Comment by Nettakrim** [comment]
![image](https://github.com/user-attachments/assets/6b8df6d6-2982-49af-8267-7f72bfc25097)
the solution i went for was just putting a "window" over the vanilla overlay, so whatever vanilla does can be seen through, but the outer frame gets covered

**Comment by Fyoncle** [comment]
> https://modrinth.com/mod/spyglass-astronomy/version/1.0.14-mc1.21.2+

I use 1.20.1 :(

**Comment by Nettakrim** [comment]
i have a bug to fix on 1.20.1 anyway, so ill backport the latest version

**Comment by Fyoncle** [comment]
> i have a bug to fix on 1.20.1 anyway, so ill backport the latest version

Lovely, thank you :D
