### ISSUE TITLE
Crash with spyglass improvements 

### ISSUE THREAD

**Issue by LysanderTron** [Nettakrim/Spyglass-Astronomy#5]
[latest.log](https://github.com/Nettakrim/Spyglass-Astronomy/files/10678720/latest.log)
https://modrinth.com/mod/spyglass-improvements

**Comment by Nettakrim** [comment]
yes, i am aware of this bug, i will look into a fix soon, but no promises

Spyglass Astronomy does have its own scroll zoom built in

**Comment by ducksper** [comment]
I just found an alternative to Spyglass Improvements that is compatible with Skyglass Astronomy: https://github.com/WerDei/Zoomglass

+Thank you @Nettakrim for this project. This is one of the most beautiful small immersive mods I've seen 🌌 👏

**Comment by Nettakrim** [comment]
ah cool, ill add a little note on the modrinth for that

**Comment by Nettakrim** [comment]
fixed, see https://github.com/Nettakrim/Spyglass-Astronomy/issues/8

**Comment by Nettakrim** [comment]
if it makes you feel any better its probably broken in 1.20 too :P

if i get around to backporting i will make sure all earlier 1.19 versions are up to date, although thatll be in a while

**Comment by Nettakrim** [comment]
I think there's another issue somewhere about this -- I'm definitely aware of the issue

There's annoyingly little i can do until i can even figure out how complementary renders stars

**Comment by Nettakrim** [comment]
wait what it does work? nvm
